apiVersion: v1
kind: Namespace
metadata:
  name: ns-posthub--env--
  labels:
    name: ns-posthub--env--

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posthub-mongo
spec:
  selector:
    matchLabels:
      app: posthub-mongo
  template:
    metadata:
      labels:
        app: posthub-mongo
    spec:
      containers:
      - name: posthub-mongo
        image: mongo
        resources:
          limits:
            memory: "2500Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
          name: posthub-mongo

---
kind: Service
apiVersion: v1
metadata:
  name: posthub-mongodb-service
  namespace: ns-posthub--env--
spec:
  selector:
    app: posthub-mongo
  ports:
  - port: 27020
    targetPort: 27017
    protocol: TCP
  type: ClusterIP
